### ISSUE TITLE
Can ping url but not ssh to container

### ISSUE THREAD

**Issue by GM-Alex** [bnfinet/docker-dns#7]
I can ping the the container by the generated url but I'm not able to login via SSH. Using the ip which I get from the ping works as expected.

**Comment by GM-Alex** [comment]
Ok found the solution. SSH tries to use IPv6. 

If you have similar issues add the following line to your ``/etc/ssh/ssh_config`` 

```
AddressFamily inet
```

@bnfinet Is there any road map for that?

**Comment by bnfinet** [comment]
@GM-Alex are you offering to test? :)

**Comment by GM-Alex** [comment]
@bnfinet Sure ;)

**Comment by bnfinet** [comment]
moving conversation to #9 
closing
